# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    build:
      context: ..
      dockerfile: db_resources/Dockerfile
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=local
      - HOST=mongo
    depends_on:
      - mongo
    volumes:
      - ../:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: competencias_enem_data
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Associando o volume nomeado
      - ./init-scripts:/docker-entrypoint-initdb.d


volumes:
  mongo_data:
    name: my_volume_mongo  # Nome personalizado para o volume

